#pragma once
#define LANG_CODE "en"
// bot connected to server/guild 
#define HELLO_TITLE "Bot available"
#define HELLO_FIELD "To learn more about me, click text above"
//commands info
#define WEATHER_COMMAND "weather"
#define WEATHER_DESC "Current weather"
#define CITY "city"
#define CITY_WEATHER_DESC "City, where you want to check the weather"
#define DAY "day"
#define HOUR "hour"
#define FORECAST_SUMMARY_COMMAND "daily-forecast"
#define FORECAST_SUMMARY_DESC "Weather forecast - daily summary"
#define FORECAST_HOUR_COMMAND "hourly-forecast"
#define FORECAST_HOUR_DESC "Weather forecast at a given hour"
#define HOUR_FORECAST_DESC "Hour (24h format), when you want to check the weather"
#define CITY_FORECAST_DESC "City, where you want to check the weather forecast"
#define DAY_FORECAST_DESC "Number of days since today to day, when you want to check forecast"
#define POLLUTION_COMMAND "air-pollution"
#define POLLUTION_DESC "Current air pollution"
#define CITY_POLLUTION_DESC "City, where you want to check the air pollution"
#define UNITS_PARAM "units"
#define UNITS_PARAM_DESC "Choose units: true for imperial(Fahrenheit etc.), false for Si(Celsius etc.), Si by default"
//slashcommand errors
#define UNKNOWN_COMMAND "Command not recognized, try again"
#define INCORRECT_DAY_AND_HOUR "Incorrect day and hour, try again(bot supports forecast of 2 days into the future)"
#define INCORRECT_DAY "Incorrect day, try again(bot supports from today to day after tomorrow)"
#define INCORRECT_HOUR "Incorrect hour, try again(input hour from 0 to 23)"
//http errors
#define UNKNOWN_HTTP_ERROR "Unknown HTTP error, try again"
#define ERROR_403 "API authorization error, contact bot maintaner/server administrator"
#define ERROR_400 "Town not found, try with a bigger, neighboring town"
#define ERROR_429 "Too many requests send, try again in a while"
//command handlers' strings
#define WEATHER_IN "Weather in "
#define WEATHER_SEARCH "https://www.ecosia.org/search?q=weather+in+"
#define DATA_COLLECTED_AT_DESC "Data collected at: "
#define COUNTRY_TITLE "Country: "
#define TEMPERATURE_TITLE "Temperature"
#define TEMPERATURE_UNIT_SI " °C"
#define TEMPERATURE_UNIT_IMP " °F"
#define FEELS_LIKE_TITLE "Feels-like temperature"
#define WIND_SPEED_TITLE "Wind speed"
#define WIND_SPEED_UNIT_SI  " km/h"
#define WIND_SPEED_UNIT_IMP  " mph"
#define WIND_DIRECTION_TITLE "Wind direction"
#define CLOUD_COVER_TITLE "Cloud cover"
#define PERCENT "%"
#define UV_TITLE "UV"
#define AIR_PRESSURE_TITLE "Air pressure"
#define AIR_PRESSURE_UNIT_SI " hpa"
#define AIR_PRESSURE_UNIT_IMP " inHg"
#define HUMIDITY_TITLE "Humidity"
#define PRECIPITATION_TITLE "Precipitation"
#define PRECIPITATION_UNIT_SI " mm"
#define PRECIPITATION_UNIT_IMP " in"
#define AIR_QUALITY_IN "Air quality in: "
#define AIR_QUALITY_SEARCH "https://www.ecosia.org/search?q=jakość+powietrza+w+"
#define AIR_QUALITY_UNIT " μg/m³"
#define CO_TITLE "CO, Carbon monoxide"
#define NO2_TITLE "NO₂ Nitrogen dioxide"
#define O3_TITLE "O₃ Ozone"
#define SO2_TITLE "SO₂ Sulphur dioxide"
#define PM2_5_TITLE "Dust < 2,5 μm"
#define PM10_TITLE "Dust < 10 μm"
#define UK_DEFRA_TITLE "British air quality index"
#define DATE "Date : "
#define IN_DAY_URL "+on+"
#define AT_HOUR_URL "+at+"
#define MAX_TEMPERATURE_TITLE "Max temperature"
#define MIN_TEMPERATURE_TITLE "Min temperature"
#define AVG_TEMPERATURE_TITLE "Average temperature"
#define MAX_WIND_SPEED_TITLE "Max wind speed"
#define AVG_HUMIDITY_TITLE "Average humidity"
#define TOTAL_PRECIPITATION_TITLE "Total precipitation"
