#pragma once
#define LANG_CODE "pl"
// bot connected to server/guild 
#define HELLO_TITLE "Bot dostępny"
#define HELLO_FIELD "Aby dowiedzieć się o mnie więcej, kliknij w tekst powyżej"
//commands info
#define WEATHER_COMMAND "pogoda"
#define WEATHER_DESC "Aktualna pogoda"
#define CITY "miasto"
#define CITY_WEATHER_DESC "Miasto(bez polskich liter), w którym chcesz sprawdzić pogodę"
#define DAY "dzień"
#define HOUR "godzina"
#define FORECAST_SUMMARY_COMMAND "prognoza-dzienna"
#define FORECAST_SUMMARY_DESC "Prognoza pogody - podsumowanie dnia"
#define FORECAST_HOUR_COMMAND "prognoza-godzinna"
#define FORECAST_HOUR_DESC "Prognoza pogody o danej godzinie"
#define HOUR_FORECAST_DESC "Godzina (format 24h), o której chcesz sprawdzić pogodę"
#define CITY_FORECAST_DESC "Miasto(bez polskich liter), w którym chcesz sprawdzić prognozowaną pogodę"
#define DAY_FORECAST_DESC "Liczba dni od dzisiaj do dnia, w którym chcesz sprawdzić prognozę"
#define POLLUTION_COMMAND "zanieczyszczenia-powietrza"
#define POLLUTION_DESC "Aktualne zanieczyszczenia powietrza"
#define CITY_POLLUTION_DESC "Miasto(bez polskich liter), w którym chcesz sprawdzić zanieczyszczenie powietrza"
#define UNITS_PARAM "jednostki"
#define UNITS_PARAM_DESC "Wybierz jednostki: true dla imperialnych, false dla jednostek układu SI(domyślnie SI)"
//slashcommand errors
#define UNKNOWN_COMMAND "Nie rozpoznano komendy, spróbuj ponownie"
#define INCORRECT_DAY_AND_HOUR "Niepoprawny dzień i godzina, spróbuj ponownie(bot wspiera prognozę do 2 dni)"
#define INCORRECT_DAY "Niepoprawny dzień, spróbuj ponownie(bot wspiera prognozę od dzisiaj do pojutrza)"
#define INCORRECT_HOUR "Niepoprawna godzina, spróbuj ponownie(podaj godznię od 0 do 23)"
//http errors
#define UNKNOWN_HTTP_ERROR "Nieznany błąd HTTP, spróbuj ponownie"
#define ERROR_403 "Błąd autoryzacji API, skontaktuj się z opiekunem bota/administratorem sewrwera"
#define ERROR_400 "Nie odnaleziono miejscowości, spróbuj z większą, sąsiednią miejscowością"
#define ERROR_429 "Wysłano zbyt wiele zapytań, spróbuj ponownie za chwilę"
//command handlers' strings
#define WEATHER_IN "Pogoda w "
#define WEATHER_SEARCH "https://www.ecosia.org/search?q=pogoda+w+"
#define DATA_COLLECTED_AT_DESC "Dane pobrano o godzinie: "
#define COUNTRY_TITLE "Państwo: "
#define TEMPERATURE_TITLE "Temperatura"
#define TEMPERATURE_UNIT_SI " °C"
#define TEMPERATURE_UNIT_IMP " °F"
#define FEELS_LIKE_TITLE "Temperatura odczuwalna"
#define WIND_SPEED_TITLE "Prędkość wiatru"
#define WIND_SPEED_UNIT_SI  " km/h"
#define WIND_SPEED_UNIT_IMP  " mph"
#define WIND_DIRECTION_TITLE "Kierunek wiatru"
#define CLOUD_COVER_TITLE "Zachmurzenie"
#define PERCENT "%"
#define UV_TITLE "UV"
#define AIR_PRESSURE_TITLE "Ciśnienie"
#define AIR_PRESSURE_UNIT_SI " hpa"
#define AIR_PRESSURE_UNIT_IMP " inHg"
#define HUMIDITY_TITLE "Wilgotność"
#define PRECIPITATION_TITLE "Opady"
#define PRECIPITATION_UNIT_SI " mm"
#define PRECIPITATION_UNIT_IMP " in"
#define AIR_QUALITY_IN "Jakość powietrza w: "
#define AIR_QUALITY_SEARCH "https://www.ecosia.org/search?q=jakość+powietrza+w+"
#define AIR_QUALITY_UNIT " μg/m³"
#define CO_TITLE "CO, Tlenek węgla(czad)"
#define NO2_TITLE "NO₂ Dwutlenek azotu"
#define O3_TITLE "O₃ Ozon"
#define SO2_TITLE "SO₂ Dwutlenek siarki"
#define PM2_5_TITLE "Pył < 2,5 μm"
#define PM10_TITLE "Pył < 10 μm"
#define UK_DEFRA_TITLE "Brytyjski indeks jakości powietrza"
#define DATE "Data : "
#define IN_DAY_URL "+w+dniu+"
#define AT_HOUR_URL "+o+godzinie+"
#define MAX_TEMPERATURE_TITLE "Maksymalna temperatura"
#define MIN_TEMPERATURE_TITLE "Minimalna temperatura"
#define AVG_TEMPERATURE_TITLE "Średnia temperatura"
#define MAX_WIND_SPEED_TITLE "Maksymalna prędkość wiatru"
#define AVG_HUMIDITY_TITLE "Średnia wilgotność"
#define TOTAL_PRECIPITATION_TITLE "Łączne opady"
